const express = require('express')
const db = require('./server.js')
const mysql = require('mysql2')
const createEtudiant =`
CREATE TABLE IF NOT EXISTS ETUDIANT (
    id INT AUTO_INCREMENT PRIMARY KEY,
    NOM VARCHAR(20) NOT NULL,
    PRENOM VARCHAR(20) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    ANNE ENUM('2','3','4','5'),
    SPECIALITE ENUM('ISI','SIW','AI'),
    MOYENNE DECIMAL(4,2) NOT NULL,
    points INT NOT NULL
);
`
const createEnseignant=`CREATE TABLE IF NOT EXISTS ENSEIGNANT (
    id INT AUTO_INCREMENT PRIMARY KEY,
    NOM VARCHAR(20) NOT NULL,
    PRENOM VARCHAR(20) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    SPECIALITE VARCHAR(20) NOT NULL
);
`
const createEntreprise=`CREATE TABLE IF NOT EXISTS ENTREPRISE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    NUMEROSOCIALE INT UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    SPECIALITE VARCHAR(20) NOT NULL
);
`
const createAdmin=`CREATE TABLE IF NOT EXISTS ADMIN (
    id INT AUTO_INCREMENT PRIMARY KEY,
    NOM VARCHAR(20) NOT NULL,
    PRENOM VARCHAR(20) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);
`
const createTheme=`CREATE TABLE IF NOT EXISTS THEME (
    id INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    TAGS TEXT NOT NULL,
    PREALABLE TINYINT(1) NOT NULL DEFAULT 0,
    SPECIALITE ENUM('ISI','SIW','AI'),
    ANNE ENUM('2','3','4','5'),
    isValid TINYINT(1) NOT NULL DEFAULT 0
);
`
const createGroupe=`CREATE TABLE IF NOT EXISTS GROUPE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ANNE ENUM('2','3','4','5') NOT NULL,
    idchef INT,
    FOREIGN KEY (idchef) REFERENCES ETUDIANT(id),
    NUMERO INT NOT NULL,
    NEEDS TEXT
);
`
const createJury=`CREATE TABLE IF NOT EXISTS JURYS (
   id INT AUTO_INCREMENT PRIMARY KEY,
   idchef INT,
   FOREIGN KEY (idchef) REFERENCES ENSEIGNANT(id),
   ANNE ENUM('2','3','4','5'),
   SPECIALITE ENUM('ISI','SIW','AI')
);
`
const createMeet=`CREATE TABLE IF NOT EXISTS MEET (
   id INT AUTO_INCREMENT PRIMARY KEY,
   DATE DATETIME NOT NULL,
   RAPPORT TEXT NOT NULL,
   ISCANCELED TINYINT(1) NOT NULL DEFAULT 0
);
`
const createNotfication=`CREATE TABLE IF NOT EXISTS NOTIFICATION (
   id INT AUTO_INCREMENT PRIMARY KEY,
   TYPE ENUM('MEET','SOUTENANCE'),
   CONTENUE TEXT NOT NULL,
   CIBLE VARCHAR(20) NOT NULL
);
`
const createDocument=`CREATE TABLE IF NOT EXISTS DOCUMENT (
   id INT AUTO_INCREMENT PRIMARY KEY,
   TYPE ENUM('PV','CAHIER_DE_CHARGE'),
   LIEN TEXT NOT NULL,
   idAuteur INT,
   FOREIGN KEY (idAuteur) REFERENCES ETUDIANT(id)
);
`
const createEvaluation=`CREATE TABLE IF NOT EXISTS EVALUATION (
   id INT AUTO_INCREMENT PRIMARY KEY,
   ISPRESENT TINYINT(1) NOT NULL DEFAULT 0,
   NOTE DECIMAL(4,2) NOT NULL,
   REMARQUE TEXT NOT NULL
);
`
const createEvaSout=`CREATE TABLE IF NOT EXISTS EVALUATION_SOUTENANCE (
   id INT AUTO_INCREMENT PRIMARY KEY,
   NOTE DECIMAL(4,2) NOT NULL,
   REMARQUE TEXT NOT NULL
);

`
module.exports.createTable=[createEtudiant,createEnseignant,createEntreprise,createTheme,createAdmin,createGroupe,createJury,createMeet,createNotfication,createDocument,createEvaluation,createEvaSout]